spring:
  datadource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

server:
  servlet:
    context-path: /ads
  port: 8080

consts:
  category: Games, Sports, Fasion, Literature, Perfume
  products_amount: 100